version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16.15.0
    commands:
      - echo node version check
      - node -v
      - npm -v
  pre_build:
    commands:
      - cd client
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    command:
      - echo post Building...
artifacts:
  files:
    - '**/*'
  base-directory: client/build
